services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    links:
     - php
    volumes: 
      - ./nginx-config:/etc/nginx/conf.d
      - ./app:/var/www/html

  php:
    image: php:8.1.4-fpm-bullseye
    volumes:
      - ./app:/var/www/html
