services:
  database:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: docker-training
    volumes:
      - ./dummy-data:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    links:
      - database