services:
  proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - ./cert:/etc/nginx/certs
    ports:
     - 80:80
     - 443:443
    restart: always

networks:
  default:
      name: nginx-proxy
